theme: osuny
_merge: deep
params:
  summary:
    position: hero
  breadcrumb:
    position: after-hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  menu:
    primary:
      level_2:
        title:
          active: true