[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/carnet/actualites/index.html"
to = "/actualites/"

[[redirects]]
from = "/portfolio/index.html"
to = "/ressources/"

[[redirects]]
from = "/fiches/index.html"
to = "/fiche/"

[[redirects]]
from = "/equipe/anat-meruk/index.html"
to = "/equipe-1/anat-meruk/"

[[redirects]]
from = "/equipe/index.html"
to = "/equipe-1/"

[[redirects]]
from = "/organisations/iccare/index.html"
to = "/partenaires/iccare/"

[[redirects]]
from = "/projets/index.html"
to = "/ressources/"

[[redirects]]
from = "/organisations/cda/index.html"
to = "/partenaires/cda/"

[[redirects]]
from = "/organisations/artec/index.html"
to = "/partenaires/artec/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/equipe-1/equipe-editoriale/"

[[redirects]]
from = "/personnes/clement-coustenoble/index.html"
to = "/equipe-1/clement-coustenoble/"

[[redirects]]
from = "/personnes/lou-vettier/index.html"
to = "/equipe-1/lou-vettier/"

[[redirects]]
from = "/personnes/clara-broussot-2/index.html"
to = "/equipe-1/clara-broussot-2/"

[[redirects]]
from = "/organisations/tmn-lab/index.html"
to = "/partenaires/tmn-lab/"

[[redirects]]
from = "/portfolio/fiches/index.html"
to = "/ressources/fiches/"

[[redirects]]
from = "/personnes/julie-peghini/index.html"
to = "/equipe-1/julie-peghini/"

[[redirects]]
from = "/organisations/le-cube-garges/index.html"
to = "/partenaires/le-cube-garges/"

[[redirects]]
from = "/personnes/thu-trinh-bouvier/index.html"
to = "/equipe-1/thu-trinh-bouvier/"

[[redirects]]
from = "/organisations/musee-dorsay/index.html"
to = "/partenaires/musee-dorsay/"

[[redirects]]
from = "/personnes/anthony-ferretti/index.html"
to = "/equipe-1/anthony-ferretti/"

[[redirects]]
from = "/equipe/sebastien-appiotti/index.html"
to = "/equipe-1/sebastien-appiotti/"

[[redirects]]
from = "/carnet/agenda/index.html"
to = "/agenda/"

[[redirects]]
from = "/personnes/albertine-meunier/index.html"
to = "/equipe-1/albertine-meunier/"

[[redirects]]
from = "/equipe/berengere-voisin/index.html"
to = "/equipe-1/berengere-voisin/"

[[redirects]]
from = "/organisations/gripic/index.html"
to = "/partenaires/gripic/"

[[redirects]]
from = "/personnes/agnes-abastado/index.html"
to = "/equipe-1/agnes-abastado/"

[[redirects]]
from = "/personnes/julien-levesque/index.html"
to = "/equipe-1/julien-levesque/"

[[redirects]]
from = "/dispositif/description/index.html"
to = "/description/"

[[redirects]]
from = "/personnes/anastasiia-baryshnikova/index.html"
to = "/equipe-1/anastasiia-baryshnikova/"

[[redirects]]
from = "/visualisations-donnees/index.html"
to = "/galerie/"

[[redirects]]
from = "/organisations/paris-8/index.html"
to = "/partenaires/paris-8/"

[[redirects]]
from = "/personnes/sebastien-appiotti/index.html"
to = "/equipe-1/sebastien-appiotti/"

[[redirects]]
from = "/personnes/sylvie-tissot/index.html"
to = "/equipe-1/sylvie-tissot/"

[[redirects]]
from = "/portfolio/references/index.html"
to = "/ressources/references/"

[[redirects]]
from = "/dispositif/visualisations/index.html"
to = "/galerie/"

[[redirects]]
from = "/personnes/berengere-voisin/index.html"
to = "/equipe-1/berengere-voisin/"

[[redirects]]
from = "/organisations/index.html"
to = "/partenaires/"

[[redirects]]
from = "/a-propos/index.html"
to = "/presentation/"

[[redirects]]
from = "/organisations/datadada/index.html"
to = "/partenaires/datadada/"

[[redirects]]
from = "/personnes/anat-meruk/index.html"
to = "/equipe-1/anat-meruk/"

[[redirects]]
from = "/personnes/camille-dauhut/index.html"
to = "/equipe-1/camille-dauhut/"

[[redirects]]
from = "/carnet/expositions/index.html"
to = "/expositions/"

