[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/carnet/actualites/"
to = "/actualites/"

[[redirects]]
from = "/portfolio/"
to = "/ressources/"

[[redirects]]
from = "/fiches/"
to = "/fiche/"

[[redirects]]
from = "/equipe/anat-meruk/"
to = "/equipe-1/anat-meruk/"

[[redirects]]
from = "/equipe/"
to = "/equipe-1/"

[[redirects]]
from = "/organisations/iccare/"
to = "/partenaires/iccare/"

[[redirects]]
from = "/projets/"
to = "/ressources/"

[[redirects]]
from = "/organisations/cda/"
to = "/partenaires/cda/"

[[redirects]]
from = "/organisations/artec/"
to = "/partenaires/artec/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/equipe-1/equipe-editoriale/"

[[redirects]]
from = "/personnes/clement-coustenoble/"
to = "/equipe-1/clement-coustenoble/"

[[redirects]]
from = "/personnes/lou-vettier/"
to = "/equipe-1/lou-vettier/"

[[redirects]]
from = "/personnes/clara-broussot-2/"
to = "/equipe-1/clara-broussot-2/"

[[redirects]]
from = "/organisations/tmn-lab/"
to = "/partenaires/tmn-lab/"

[[redirects]]
from = "/portfolio/fiches/"
to = "/ressources/fiches/"

[[redirects]]
from = "/personnes/julie-peghini/"
to = "/equipe-1/julie-peghini/"

[[redirects]]
from = "/organisations/le-cube-garges/"
to = "/partenaires/le-cube-garges/"

[[redirects]]
from = "/personnes/thu-trinh-bouvier/"
to = "/equipe-1/thu-trinh-bouvier/"

[[redirects]]
from = "/organisations/musee-dorsay/"
to = "/partenaires/musee-dorsay/"

[[redirects]]
from = "/personnes/anthony-ferretti/"
to = "/equipe-1/anthony-ferretti/"

[[redirects]]
from = "/equipe/sebastien-appiotti/"
to = "/equipe-1/sebastien-appiotti/"

[[redirects]]
from = "/carnet/agenda/"
to = "/agenda/"

[[redirects]]
from = "/personnes/albertine-meunier/"
to = "/equipe-1/albertine-meunier/"

[[redirects]]
from = "/equipe/berengere-voisin/"
to = "/equipe-1/berengere-voisin/"

[[redirects]]
from = "/organisations/gripic/"
to = "/partenaires/gripic/"

[[redirects]]
from = "/personnes/agnes-abastado/"
to = "/equipe-1/agnes-abastado/"

[[redirects]]
from = "/personnes/julien-levesque/"
to = "/equipe-1/julien-levesque/"

[[redirects]]
from = "/dispositif/description/"
to = "/description/"

[[redirects]]
from = "/personnes/anastasiia-baryshnikova/"
to = "/equipe-1/anastasiia-baryshnikova/"

[[redirects]]
from = "/visualisations-donnees/"
to = "/galerie/"

[[redirects]]
from = "/organisations/paris-8/"
to = "/partenaires/paris-8/"

[[redirects]]
from = "/personnes/sebastien-appiotti/"
to = "/equipe-1/sebastien-appiotti/"

[[redirects]]
from = "/personnes/sylvie-tissot/"
to = "/equipe-1/sylvie-tissot/"

[[redirects]]
from = "/portfolio/references/"
to = "/ressources/references/"

[[redirects]]
from = "/dispositif/visualisations/"
to = "/galerie/"

[[redirects]]
from = "/personnes/berengere-voisin/"
to = "/equipe-1/berengere-voisin/"

[[redirects]]
from = "/organisations/"
to = "/partenaires/"

[[redirects]]
from = "/a-propos/"
to = "/presentation/"

[[redirects]]
from = "/organisations/datadada/"
to = "/partenaires/datadada/"

[[redirects]]
from = "/personnes/anat-meruk/"
to = "/equipe-1/anat-meruk/"

[[redirects]]
from = "/personnes/camille-dauhut/"
to = "/equipe-1/camille-dauhut/"

[[redirects]]
from = "/carnet/expositions/"
to = "/expositions/"

